language: go

go:
  - 1.7
  - 1.8
  - tip

matrix:
    allow_failures:
        - go: tip

install:
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - mkdir -p $GOPATH/src/gopkg.in/src-d
  - mv $(pwd) $GOPATH/src/gopkg.in/src-d/proteus.v1
  - cd $GOPATH/src/gopkg.in/src-d/proteus.v1
  - go get -t -v ./...

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
